image: theyoctojester/yocto-esdk:qemuarm

tasks:
  - name: Prebuild image
    init: source ~/poky_sdk/environment-setup*
    prebuild: git submodule init && git submodule update

ports:
  - port: 2222
    visibility: private
  - port: 2323
    onOpen: ignore
  - port: 5900
    onOpen: ignore
  - port: 6080
    onOpen: open-preview